---
include:
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nrf52840dongle_nrf52840
    shield: dongle_display
